### ISSUE TITLE
Releases for latest 5.x versions missing

### ISSUE THREAD

**Issue by muffix** [codelibs/elasticsearch-cluster-runner#31]
Hi there,

I had a look at the [Maven repo](https://repo1.maven.org/maven2/org/codelibs/elasticsearch-cluster-runner/) linked in the `README` (it's actually an outdated link, PR incoming) and it seems that the latest version for Elastic 5.x is `5.6.10.0`.

Elastic has since released versions `5.6.11` through `5.6.16`. Would it be possible to get releases for the cluster runner for these versions or at least for the latest, `5.6.16`? I'd like to update an Elastic plugin that uses the cluster runner for its tests.

**Comment by marevol** [comment]
I pushed 5.6.16 to the repository. It'll be available.

**Comment by muffix** [comment]
Thanks for the quick response @marevol. 🙌 I can't see the updated version in Maven yet; does it just take some time to sync?

**Comment by marevol** [comment]
hmm..., I do not know why I cannot deploy it...
just in case, I deployed version 5.6.16.1.

**Comment by muffix** [comment]
Looking at the [build log](https://travis-ci.org/codelibs/elasticsearch-cluster-runner/builds/645017962), it fails to install OpenJDK. I think it's related to Travis' recent change to use Ubuntu Xenial as the build environment: https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment

Options are to update to OpenJDK 8 or pin the distribution to Trusty in the Travis config by adding `dist: trusty`. #33 makes the build use OpenJDK. This is in line with the master branch.

**Comment by marevol** [comment]
The deployment problem is in Sonatype. 
So, travis error is not related to the problem I encountered.

**Comment by muffix** [comment]
What's the error you're seeing? Anything you can use help with?

**Comment by sabi0** [comment]
Hi,
Any chance to have recent 6.8.x builds too?
The latest is 6.8.4.0. And Elastic is already on 6.8.9.
(Should I create a separate ticket?)

**Comment by marevol** [comment]
released.
