### ISSUE TITLE
Release for latest 6.x version

### ISSUE THREAD

**Issue by seraphr** [codelibs/elasticsearch-cluster-runner#45]
Hi,

I cannot find elasticsearch-cluster-runner for elasticsearch 6.8.23 in [maven-central](https://repo1.maven.org/maven2/org/codelibs/elasticsearch-cluster-runner/) and [codelibs-repo](https://maven.codelibs.org/org/codelibs/elasticsearch-cluster-runner/).
can you please release elasticsearch-cluster-runner for elasticsearch 6.8.23?

**Comment by marevol** [comment]
We have no plan to release it for elasticsearch 6.

**Comment by seraphr** [comment]
Oh, that's sad.
